/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.LoginDao;
import dbutil.DBConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mehul
 */
public class LoginOptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginOptionsFrame
     */
    public LoginOptionsFrame() {
        initComponents();
          this.setLocationRelativeTo(null);
    }
 Connection conn=DBConnection.getConnection();
 
 
 private String getUserType() {
        if(btnLogin.isSelected())
            return btnLogin.getText().toLowerCase();

        else
            return null;
    }
 
 private String getUserType1() {
        if(btnLogin1.isSelected())
            return btnLogin1.getText().toLowerCase();

        else
            return null;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        P2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtUserId1 = new javax.swing.JTextField();
        txtPassword1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        btnLogin1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        P1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblCashier = new javax.swing.JLabel();
        lblQuit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        P2.setBackground(new java.awt.Color(0, 0, 0));
        P2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        P2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Login ID");

        txtUserId1.setBackground(new java.awt.Color(51, 51, 51));
        txtUserId1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUserId1.setForeground(new java.awt.Color(255, 255, 255));
        txtUserId1.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.inactiveForeground"), 3, true));

        txtPassword1.setBackground(new java.awt.Color(51, 51, 51));
        txtPassword1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPassword1.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword1.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.inactiveForeground"), 3, true));
        txtPassword1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password");

        btnLogin1.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLogin1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin1.setIcon(new javax.swing.ImageIcon("D:\\netbeans\\Java\\Icons\\Login\\fingerprints (4).png")); // NOI18N
        btnLogin1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        btnLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogin1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogin1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogin1MouseExited(evt);
            }
        });
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGER");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        javax.swing.GroupLayout P2Layout = new javax.swing.GroupLayout(P2);
        P2.setLayout(P2Layout);
        P2Layout.setHorizontalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(P2Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(P2Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtUserId1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(P2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        P2Layout.setVerticalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserId1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnLogin1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(P2, "card2");

        P1.setBackground(new java.awt.Color(204, 204, 204));
        P1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Login ID");

        txtUserId.setBackground(new java.awt.Color(51, 51, 51));
        txtUserId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUserId.setForeground(new java.awt.Color(255, 255, 255));
        txtUserId.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.inactiveForeground"), 3, true));

        txtPassword.setBackground(new java.awt.Color(51, 51, 51));
        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("TextField.inactiveForeground"), 3, true));
        txtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Password");

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon("D:\\netbeans\\Java\\Icons\\Login\\fingerprints (4).png")); // NOI18N
        btnLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMIN");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(P1Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(P1Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(P1, "card2");

        lblAdmin.setBackground(new java.awt.Color(0, 0, 0));
        lblAdmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdmin.setText("ADMIN");
        lblAdmin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        lblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAdminMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAdminMouseReleased(evt);
            }
        });

        lblCashier.setBackground(new java.awt.Color(0, 0, 0));
        lblCashier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCashier.setForeground(new java.awt.Color(255, 255, 255));
        lblCashier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCashier.setText("MANAGER");
        lblCashier.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        lblCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCashierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCashierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCashierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCashierMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblCashierMouseReleased(evt);
            }
        });

        lblQuit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblQuit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuit.setText("X");
        lblQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuitMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 153));
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\netbeans\\Java\\Icons\\oie_oie_canvas.png")); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        btnLogin.setBackground(Color.blue);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        btnLogin.setBackground(Color.red);
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        btnLogin.setBackground(Color.black);
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        
         if(validateInput()==true )
        {
            JOptionPane.showMessageDialog(null, "insert input in all fields","Empty values!",JOptionPane.ERROR_MESSAGE);
            return;
        }

         try
        {     
       String username = txtUserId.getText().toLowerCase().trim();
        String password =txtPassword.getText();
        
       ResultSet rs = new LoginDao().AdminLogin(username, password);
       
            if(rs.next())
            {
               
                
                AdminOptionsFrame options = new AdminOptionsFrame();
                options.setVisible(true);
                this.dispose();

                JOptionPane.showMessageDialog(null,"WellCome Boss");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "username and password do not matched");
            }
        }
      
        
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Please input numeric values","Input Error!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Error in sql"+ex,"Error!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } 
         catch (Exception ex) {
            Logger.getLogger(LoginOptionsFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
  

 /*
        
        String sql="select * from adminlogin where username=? and password=? ";
        try
        {

            PreparedStatement pst= conn.prepareStatement(sql);

            pst.setString(1, txtUserId.getText().toLowerCase().trim());//

            pst.setString(2,txtPassword.getText().toLowerCase().trim());

            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {

                AdminOptionsFrame options = new AdminOptionsFrame();
                options.setVisible(true);
                this.dispose();

                JOptionPane.showMessageDialog(null,"WellCome Boss");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "username and password do not matched");
            }
        }
        catch(SQLException  ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }}
         */

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogin1MouseClicked
        btnLogin1.setBackground(Color.blue);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin1MouseClicked

    private void btnLogin1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogin1MouseEntered
        // TODO add your handling code here:
        btnLogin1.setBackground(Color.blue);
    }//GEN-LAST:event_btnLogin1MouseEntered

    private void btnLogin1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogin1MouseExited
        // TODO add your handling code here:
        btnLogin1.setBackground(Color.black);
    }//GEN-LAST:event_btnLogin1MouseExited

    
    
    
    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        // TODO add your handling code here:
                  if(validateInput1()==true )
        {
            JOptionPane.showMessageDialog(null, "insert input in all fields","Empty values!",JOptionPane.ERROR_MESSAGE);
            return;
        }
       
 try
        {     
       String username = txtUserId1.getText();
       String password =txtPassword1.getText();
        
       ResultSet rs = new LoginDao().ManagerLogin(username, password);
       
           if(rs.next())
           {
      
                OptionsFrame options = new OptionsFrame();
                options.setVisible(true);
                this.dispose();

                JOptionPane.showMessageDialog(null,"WellCome Employee");
            }
           
            else
            {
                JOptionPane.showMessageDialog(null, "username and password do not matched");
            }
        }
      
        
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Please input numeric values","Input Error!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Error in sql"+ex,"Error!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } 
         catch (Exception ex) {
            Logger.getLogger(LoginOptionsFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
      /*  
        
        String sql="select * from employeelogin where username=? and password=?";
        try
        {

            PreparedStatement pst= conn.prepareStatement(sql);

            pst.setString(1, txtUserId1.getText());//.toUpperCase()

            pst.setString(2,txtPassword1.getText());
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {

                OptionsFrame options = new OptionsFrame();
                options.setVisible(true);
                this.dispose();
                JOptionPane.showMessageDialog(null,"WellCome Employee");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "username and password do not matched");
            }
        }
        catch(SQLException  ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }*/
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void lblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseClicked
        // TODO add your handling code here:
        P1.setVisible(true);
        P2.setVisible(false);
    }//GEN-LAST:event_lblAdminMouseClicked

    private void lblAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseEntered
        // TODO add your handling code here:
        lblAdmin.setForeground(Color.red);
    }//GEN-LAST:event_lblAdminMouseEntered

    private void lblAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseExited
        lblAdmin.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_lblAdminMouseExited

    private void lblAdminMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseReleased
        // TODO add your handling code here:
        P1.setVisible(true);
        P2.setVisible(false);
    }//GEN-LAST:event_lblAdminMouseReleased

    private void lblCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCashierMouseClicked
        // TODO add your handling code here:
        P2.setVisible(true);
        P1.setVisible(false);
    }//GEN-LAST:event_lblCashierMouseClicked

    private void lblCashierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCashierMouseEntered
        // TODO add your handling code here:
        lblCashier.setForeground(Color.red);
    }//GEN-LAST:event_lblCashierMouseEntered

    private void lblCashierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCashierMouseExited
        lblCashier.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_lblCashierMouseExited

    private void lblCashierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCashierMousePressed
        P2.setVisible(true);
        P1.setVisible(false);
        //JOptionPane.showMessageDialog(null,"Zyada Sai Dabane Se Kuch NAi Hoga Kaam Kar Chup Chap");        // TODO add your handling code here:
    }//GEN-LAST:event_lblCashierMousePressed

    private void lblCashierMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCashierMouseReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_lblCashierMouseReleased

    private void lblQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuitMouseClicked
        // TODO add your handling code here:

        DBConnection.closeConnection();

        System.exit(0);
    }//GEN-LAST:event_lblQuitMouseClicked

    private void lblQuitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuitMouseEntered
        // TODO add your handling code here:
        lblQuit.setForeground(Color.red);
    }//GEN-LAST:event_lblQuitMouseEntered

    private void lblQuitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuitMouseExited
        // TODO add your handling code here:
        lblQuit.setForeground(Color.red);
    }//GEN-LAST:event_lblQuitMouseExited

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        // TODO add your handling code here:
         int kordinatX = evt .getXOnScreen();
int kordinatY = evt.getYOnScreen();

this.setLocation( kordinatX, kordinatY);

    }//GEN-LAST:event_jLabel3MouseDragged

      // TODO add your handling code here: 
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginOptionsFrame().setVisible(true);
            }
        });
    }
      private boolean validateInput(){
        if(txtUserId.getText().isEmpty() || txtPassword.getText().isEmpty() )
            return true;
        else
            return false;
    }
      
      
      private boolean validateInput1(){
        if(txtUserId1.getText().isEmpty() || txtPassword1.getText().isEmpty() )
            return true;
        else
            return false;
    }

      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P1;
    private javax.swing.JPanel P2;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblCashier;
    private javax.swing.JLabel lblQuit;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUserId1;
    // End of variables declaration//GEN-END:variables
}
